/* Create database : ibDmarcosAntigos       */
CREATE DATABASE 'D:\bkp\dmarcos\FB\DMARCOS.FDB' USER 'SYSDBA' PASSWORD 'dmmaster' PAGE_SIZE 16384 ;

/***********************************/
/*         External Functions      */
/***********************************/

DECLARE EXTERNAL FUNCTION LOWER
 CSTRING(80)
  RETURNS CSTRING(80) FREE_IT 
  ENTRY_POINT 'IB_UDF_lower'
  MODULE_NAME 'ib_udf';

/***********************************/
/*              Tables             */
/***********************************/

CREATE TABLE CLIENTE (
       CODIGO_CLIENTE Smallint NOT NULL,
       NOME_CLIENTE Varchar(60),
       ENDERECO_CLIENTE Varchar(40),
       NUMERO_CLIENTE Varchar(6),
       TELEFONE_CLIENTE Varchar(15),
       FAX_CLIENTE Varchar(15),
       COMPL_END_CLIENTE Varchar(21),
       BAIRRO_CLIENTE Varchar(25),
       CEP_CLIENTE Varchar(9),
       CIDADE_CLIENTE Varchar(25),
       ESTADO_CLIENTE Varchar(2),
       CODIGO_ATV_CLIENTE Varchar(4),
       CODIGO_PAIS_CLIENTE Varchar(3),
       CPF_REPRES_CLIENTE Varchar(14),
       INSC_SUFRAMA_CLIENTE Varchar(12),
       INSC_ESTADUAL_CLIENTE Varchar(12),
       INSC_MUNICIPAL_CLIENTE Varchar(12),
       INSC_CGC_CLIENTE Varchar(18),
       DATA_CAD_CLIENTE Date,
       USUARIO_CADASTROU Varchar(30),
       DATA_ALT_CLIENTE Date,
       USUARIO_ALTERACAO Varchar(30),
       SIGLA_CLIENTE Varchar(2),
       LT_MAR Smallint,
       LT_AER Smallint,
       OBS_CLIENTE Blob SUB_TYPE 1,
       NOME_DIRETOR Varchar(40),
       FONE_DIRETOR Varchar(8),
       NOME_GER_IMPORT Varchar(40),
       FONE_GER_IMPORT Varchar(3),
       NOME_FATURAMENTO Varchar(40),
       FONE_FATURAMENTO Varchar(8),
       OUTRO_IMPORTACAO Varchar(40),
       FONE_OUTRO_IMPORT Varchar(8),
       STATUS_CLIENTE Varchar(1),
       ULTIMA_NOTA Varchar(6),
       DATA_EMI_NOTA Date,
       DATA_MOVIMENTO Date,
       CODIGO_BANCO Smallint,
       CONTA_CLIENTE Varchar(13),
       CONTA_ISS Varchar(13),
       CONTA_IRRF Varchar(13),
       ALIQ_CONT_IRRF_CLIENTE Double precision,
       ALIQ_CONT_ISS_CLIENTE Double precision,
       VALOR_NOTA Double precision,
       SISCOMEX_BANCO Varchar(3),
       SISCOMEX_AGENCIA Varchar(4),
       SISCOMEX_CONTA Varchar(19),
       USERNAME Varchar(10),
       SENHA Varchar(10),
       IMPORT Varchar(1),
       COMISSAO Double precision,
       TIPO_COMISSAO Varchar(1),
       VALOR_MINIMO Double precision,
       VALOR_MAXIMO Double precision,
       SALDO_ANT_REEMBOLSO Numeric(15,2) DEFAULT 0,
       SALDO_ANT_SERVICO Numeric(15,2) DEFAULT 0,
       SALDO_ATUAL_REEMBOLSO Numeric(15,2) DEFAULT 0,
       SALDO_ATUAL_SERVICO Numeric(15,2) DEFAULT 0,
       DI_FATURAMENTO Char(1) DEFAULT 'R',
       CALCULA_IMP_IRF_10 Char(1) DEFAULT 'S' NOT NULL,
       QTD_ITENS_NOTA Smallint DEFAULT 12 NOT NULL,
       USRALT Varchar(15),
       DEDUCOES_SOCIAIS Char(1) DEFAULT 'S' NOT NULL,
       LIMITE_DIAS_BOLETO Smallint DEFAULT 30 NOT NULL,
       NR_INSC_MIN_AGRIC Varchar(10),
       E_MAIL Varchar(80),
       IN_DESEMBARACO_SEFAZ Char(1) DEFAULT 'N' NOT NULL,
       IN_PRESTACAO_CONTA Char(1) DEFAULT 'N' NOT NULL,
       CD_MUNICIPIO Varchar(7) DEFAULT '1302603',
       DT_PROCURACAO Date,
       RESP_PROCURACAO Varchar(40),
       NR_COD_SISPLI Integer,
       IN_CIENCIA Char(1) DEFAULT 'N' NOT NULL,
       IN_CIENCIA_PROCURACAO Char(1) DEFAULT 'N' NOT NULL,
       NM_FORMULA_SEGURO Varchar(50),
       CD_MOEDA_SEGURO Char(3),
       TP_CLIENTE Char(1) DEFAULT 'J' NOT NULL,
       IN_CAPATAZIA_FRETE Char(1) DEFAULT 'N' NOT NULL,
       IN_TX_SUFRAMA_DAI Char(1) DEFAULT 'N' NOT NULL,
       CALCULA_CSSL_10 Char(1) DEFAULT 'S' NOT NULL,
       IN_EMITE_BOLETO Char(1) DEFAULT 'S' NOT NULL,
       IN_EXONERA_ICMS Char(1) DEFAULT 'S' NOT NULL,
       INDICE_ARMAZENAGEM_CALOI Double precision DEFAULT 0.01 NOT NULL,
       IN_TX_SISCOMEX_ANTIGA Char(1) DEFAULT 'N' NOT NULL,
       NR_PROCESSO_TX_SISCOMEX Varchar(20),
       IN_COMERCIO_PRESTADOR Char(1) DEFAULT 'N' NOT NULL,
       IN_SALARIO_MINIMO Char(1) DEFAULT 'N' NOT NULL,
       ALIQ_CONT_PIS_CLIENTE Double precision DEFAULT 0.65 NOT NULL,
       ALIQ_CONT_COFINS_CLIENTE Double precision DEFAULT 3 NOT NULL,
       ALIQ_CONT_CSLL_CLIENTE Double precision DEFAULT 1 NOT NULL,
       DT_CARTA_PROPOSTA Date,
       IN_PROJETO_MXM_RPS Char(1) DEFAULT 'N' NOT NULL,
       PRIMARY KEY (CODIGO_CLIENTE)
);

CREATE TABLE EMPRESA (
       CODIGO_EMPRESA Varchar(3),
       NOME_EMPRESA Varchar(50),
       QTDE_LINHAS_NOTA Integer,
       QTDE_CAR_LINHA_NOTA Integer,
       DATA_MOVIMENTO Date,
       ENTRADAS Double precision,
       SAIDAS Double precision,
       SALDO_ATUAL Double precision,
       TAXA_CPMF Double precision,
       VERSAO_EXPORT Smallint,
       VERSAO_IMPORT Smallint,
       VERSAO_ADMIN Smallint,
       SALDO_ANTERIOR Double precision,
       VERSAO_ATIVO Smallint NOT NULL,
       DSP_NM Varchar(40),
       DSP_REGISTRO Varchar(40),
       DSP_RG Varchar(80),
       DSP_CPF Varchar(20),
       VERSAO_PROCESSO Smallint NOT NULL,
       DSP_NM_PORTO Varchar(40),
       DSP_REGISTRO_PORTO Varchar(60),
       DSP_RG_PORTO Varchar(80),
       DSP_CPF_PORTO Varchar(20),
       BSB_CGC_EMPRESA Varchar(14),
       BSB_CDINSC Varchar(2),
       BSB_AG_EMPR Varchar(20),
       BSB_CTCORR Varchar(8),
       BSB_ENDOSSO Char(1),
       BSB_COD_CD_EMP Varchar(14),
       BSB_CARTEIRA Char(1),
       BSB_ESPECIE Char(2),
       BSB_CART_NUM Char(1),
       BSB_PREFIXO Char(2),
       BSB_CODREM Char(1) DEFAULT '1',
       BSB_LITREM Varchar(7) DEFAULT 'REMESSA',
       BSB_CODSERV Varchar(2) DEFAULT '01',
       BSB_LIMSERV Varchar(15) DEFAULT 'COBRANCA',
       BSB_CODAGE Varchar(3) DEFAULT '260',
       BSB_ESP0 Char(1) DEFAULT '0',
       BOLETO_BANCO Integer NOT NULL,
       VERSAO_CONTROL Smallint DEFAULT 1,
       NM_SIGLA Varchar(10) DEFAULT 'DMARCOS',
       VERSAO_EXPORT_NEW Smallint DEFAULT 1 NOT NULL,
       VERSAO_UPDATE_TECA Smallint DEFAULT 0 NOT NULL,
       DT_SEFAZ Date,
       HR_1_SEFAZ Char(5),
       HR_2_SEFAZ Char(5),
       HR_3_SEFAZ Char(5),
       HR_4_SEFAZ Char(5),
       HR_1_ADMIN Char(5),
       HR_2_ADMIN Char(5),
       VERSAO_SCSERVICO Smallint DEFAULT 1 NOT NULL,
       DESC_AEREA Blob SUB_TYPE 1,
       DESC_MARITIMA Blob SUB_TYPE 1,
       DESC_RODOVIARIO Blob SUB_TYPE 1,
       VERSAO_INTERNA Smallint DEFAULT 1 NOT NULL,
       NM_E_MAIL_TX_PIONEER Blob SUB_TYPE 1,
       DT_AVISO_CARTA_PROPOSTA Date
);

CREATE TABLE IMPORTACAO (
       CODIGO_CLIENTE Smallint NOT NULL,
       CODIGO_PROCESSO Integer NOT NULL,
       NUMERO_DA Varchar(12),
       IDT_DI Varchar(14),
       IDT_EMBARQUE Varchar(14),
       MOD_DESPACHO Varchar(1),
       VIA_TRANSPORTE Varchar(1),
       UTILIZACAO Varchar(1),
       NOME_TRANSPORTADOR Varchar(40),
       BANDEIRA_TANSP Varchar(3),
       NM_VEICULO_TRANSP Varchar(30),
       NR_VEICULO_TRANSP Varchar(15),
       DOC_CHEGADA Varchar(1),
       NUMERO_DOC_CHEGADA Varchar(15),
       TIPO_CONHECIMENTO Varchar(2),
       LOCAL_EMBARQUE Varchar(40),
       DATA_EMBARQUE Date,
       TIPO_DE_DI Varchar(2),
       APLIC_INDUS Varchar(1),
       APLIC_USO Varchar(1),
       APLIC_COMER Varchar(1),
       APLIC_PBB Char(1),
       APLIC_N_PPB Char(1),
       APLIC_PROEX Varchar(1),
       PAIS_PROCEDENCIA Varchar(3),
       PESO_BRUTO Double precision,
       PESO_LIQUIDO Double precision,
       AGENTE_TRANSPORTADOR Varchar(15),
       URF_DESPACHO Varchar(7),
       URF_DE_ENTRADA Varchar(7),
       NUMERO_DI Varchar(16),
       DATA_CHEGADA Date,
       RECINTO_ALFADEGADO Varchar(7),
       LOCAL_ARMAZEN Varchar(1),
       SETOR_ALFADEGADO Varchar(3),
       DATA_ABERTURA Date,
       VALOR_FOB_LOC_EMB Double precision,
       VALOR_FOB_MOEDA_NAC Double precision,
       MOEDA_FOB Varchar(3),
       MESMA_MOEDA_COND_VENDA Varchar(1),
       VALOR_FRETE_PRAPAID Double precision,
       VALOR_FRETE_COLECT Double precision,
       VALOR_FRETE_MOEDA_NAC Double precision,
       MOEDA_FRETE Varchar(3),
       VALOR_FRETE_TER_NAC Double precision,
       VALOR_SEGURO Double precision,
       MOEDA_SEGURO Varchar(3),
       VALOR_SEGURO_MOEDA_NAC Double precision,
       DATA_DA_DI Date,
       DATA_LIBERACAO Date,
       DATA_ENTRADA_SEFAZ Date,
       DATA_SAIDA_SEFAZ Date,
       QTDE_VOLUMES Integer,
       VALOR_CIF Double precision,
       STATUS_PROCESSO Varchar(1),
       ABERTO_POR Varchar(10),
       DATA_RECEBIMENTO Date,
       DATA_ENVIO Date,
       DATA_RECPCAO Date,
       DATA_PARAM Date,
       NOME_FISCAL Varchar(20),
       CANAL Varchar(1),
       CAIXA Varchar(6),
       DATA_ARQUIVO Date,
       DT_PAG_CAP Date,
       ALERTA Blob SUB_TYPE 1,
       INFO_COMPLEMENTARES Blob SUB_TYPE 1,
       PENDICIA_MAPA Blob SUB_TYPE 1,
       HISTORICO Blob SUB_TYPE 1,
       TAXA_UTILIZACAO_SISCOMEX Double precision,
       DAT_FEC_CAMBIO Date,
       NRO_CONTRATO_CAMBIO Varchar(12),
       DATA_MANTRA Date,
       TIPO_PROCESSO Varchar(1),
       QTDE_ADICOES Smallint,
       PRIORIDADE Varchar(1),
       DATA_PRIORIDADE Date,
       ICOTERM Varchar(3),
       TAXA_DOLAR_DI Double precision,
       PGTO_360_DIAS Varchar(1),
       TAXA_SUFRAMA Numeric(15,2),
       REG_UPDATE Char(1) DEFAULT 'N' NOT NULL,
       QTDE_NCM Smallint DEFAULT 0,
       ACAO_FISCAL Char(1) DEFAULT 'N' NOT NULL,
       DI_INTERNA Char(1) DEFAULT 'S' NOT NULL,
       PLI_INTERNO Char(1) DEFAULT 'N' NOT NULL,
       DI_HR_REGISTRO Char(5),
       ENTRADA_MIN_AGRIC Date,
       SAIDA_MIN_AGRIC Date,
       NR_NIC1 Varchar(18),
       NR_NIC2 Varchar(18),
       NUMERO_MASTER Varchar(18),
       NUMERO_FILHOTE Varchar(18),
       VALOR_THC Double precision DEFAULT 0 NOT NULL,
       VALOR_FOB_PEXPAM Double precision DEFAULT 0,
       DT_CONFERENCIA Date,
       USR_CONFERENCIA Varchar(15),
       LACRE Varchar(12),
       CD_ARMADOR Integer,
       NM_EXPORTADOR Varchar(60),
       DT_ENTRAGA_TRANSPORTADOR Date,
       DT_PLI Date,
       DT_LI Date,
       NM_MOD_VALFILME Varchar(20),
       NM_AGENTE_CARGA Varchar(30),
       INS_OLD Varchar(12),
       INSCRICAO_SEFAZ Varchar(12),
       IN_CONSOLIDADO Char(1) DEFAULT 'N' NOT NULL,
       IN_DI_COMPLEMENTAR Char(1) DEFAULT 'N' NOT NULL,
       CANAL_SEFAZ Char(1) DEFAULT 'N' NOT NULL,
       IN_MULTIMODAL Char(1) DEFAULT 'N' NOT NULL,
       IN_DAI_RETIFICADOR Char(1) DEFAULT 'N' NOT NULL,
       CD_PORTO_CHEGADA Char(1),
       IN_TERMO_INSENCAO Char(1) DEFAULT 'N' NOT NULL,
       DT_COMPLEMENTAR Date,
       VL_OUTROS_ACRESCIMO Numeric(15,2) DEFAULT 0 NOT NULL,
       IN_AGENTE_HECNY Char(1) DEFAULT 'N' NOT NULL,
       VL_MULTA Numeric(15,2) DEFAULT 0 NOT NULL,
       COMENT_MULTA Varchar(40),
       CD_MOEDA_THC Varchar(3),
       CD_MOEDA_OUT_ACRESCIMO Varchar(3),
       VL_THC_MOEDA Numeric(15,2),
       VL_OUT_ACRESCIMO_MOEDA Numeric(15,2),
       HR_ENTREGA Char(5),
       HR_CHEGADA Char(5),
       CD_MOEDA_OUT2_ACRESCIMO Varchar(3),
       VL_OUT2_ACRESCIMO_MOEDA Numeric(15,2) DEFAULT 0,
       VL_OUT2_ACRESCIMO Numeric(15,2) DEFAULT 0,
       IN_PROJETO_MXM Char(1) DEFAULT 'N' NOT NULL,
       NR_PROJETO_MXM Varchar(30),
       APLIC_REVENDA Char(1) DEFAULT 'N' NOT NULL,
       IN_TESOURARIA_MXM Char(1) DEFAULT 'N' NOT NULL,
       DT_RETIFICACAO_DI Date,
       IN_OUTRAS_TAXAS Char(1) DEFAULT 'N' NOT NULL,
       CD_MET_VALOR_ADUANEIRO Char(2) DEFAULT '01' NOT NULL,
       IN_PGTO_TRIBUTOS_DARF Char(1) DEFAULT 'N' NOT NULL,
       DT_PAGAMENTO_DARF Date,
       IN_CORBT_CAMBIAL_MISTA Char(1) DEFAULT 'N' NOT NULL,
       IN_SEM_COBERTURA_CAMBIAL Char(1) DEFAULT 'N' NOT NULL,
       NM_LOC_COND_VENDA Varchar(30),
       IN_TP_VINCULO_PRECO Varchar(1),
       PIS_CODIGO Smallint,
       PIS_FUNDAMENTO Smallint,
       CD_COND_MERCADORIA Char(1) DEFAULT 0 NOT NULL,
       CD_APLIC_MERCADORIA Smallint DEFAULT 0 NOT NULL,
       NR_ROF Varchar(8),
       CD_MOTIVO_ADM_TEMPORARIA Smallint DEFAULT 0 NOT NULL,
       IN_TP_CONTA_BANCO_SISCOMEX Char(1) DEFAULT 'P' NOT NULL,
       SISCOMEX_BANCO Varchar(3),
       SISCOMEX_AGENCIA Varchar(5),
       SISCOMEX_CONTA Varchar(19),
       IN_CONTA_DMARCOS Char(1) DEFAULT 'N' NOT NULL,
       VL_TX_AFMM Numeric(15,2) DEFAULT 0 NOT NULL,
       IN_SAIDA_ENTREPOSTO Char(1) DEFAULT 'N' NOT NULL,
       IN_ERRO_VMLE Char(1) DEFAULT 'N' NOT NULL,
       NM_EMBARQUES_CONSOLIDADOS Varchar(80),
       NR_PROTOCOLO_REGISTRO Varchar(15),
       IN_ROBO_ENTREGUE Char(1) DEFAULT 'N' NOT NULL,
       IN_ROBO_REGISTRO Char(1) DEFAULT 'N' NOT NULL,
       IN_ROBO_COMPROVANTE Char(1) DEFAULT 'N' NOT NULL,
       IN_DI_XML_CONSULTA Char(1) DEFAULT 'N' NOT NULL,
       IN_LETRA_HOUSE Char(1) DEFAULT 'N' NOT NULL,
       NM_OUTRO_ARMAZEM Varchar(15),
       NM_OUTRO_ARMAZEM_CHEGADA Varchar(15),
       VL_CUBAGEM_CARGA Double precision DEFAULT 0,
       CPF_DAI Varchar(11),
       TP_CONTAINER Char(1) DEFAULT '0' NOT NULL,
       NM_SITUACAO_DESPACHOS Varchar(63),
       NM_ETAPA_DESPACHOS Varchar(60),
       IN_ANALISE_FISCAL Char(1) DEFAULT 'N' NOT NULL,
       DT_EXIGENCIA_FISCAL Date,
       GNRE_VL_TOT_CRED Numeric(15,2),
       GNRE_CD_TRIBUTO Varchar(4),
       GNRE_NR_EXTRATO Varchar(12),
       GNRE_NR_TRIBUTO Varchar(4),
       GNRE_VL_APROVEITAMENTO Numeric(15,2),
       NR_CNPJ_ADQUIRENTE Varchar(14),
       DT_CHEGADA_MANAUS Date,
       IN_CONSUMO_ADMISSAO Char(1) DEFAULT 'N' NOT NULL,
       NFE_VL_DESP_ACESSORIAS Double precision DEFAULT 0,
       CD_MOEDA_OUT3_ACRESCIMO Varchar(3),
       VL_OUT3_ACRESCIMO_MOEDA Numeric(15,2) DEFAULT 0,
       VL_OUT3_ACRESCIMO Numeric(15,2) DEFAULT 0,
       DT_REC_INST_PLI Date,
       NM_OBS_LI Varchar(50),
       PRIMARY KEY (CODIGO_PROCESSO)
);

CREATE TABLE IMP_DI_COMPLEMENTAR (
       CD_PROCESSO Integer NOT NULL,
       NR_DI Varchar(12) NOT NULL,
       CONSTRAINT PK_IMP_DI_COMPLEMENTAR PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_DI_DA_ITEM (
       NR_DA Varchar(10) NOT NULL,
       NR_ADICAO_DA Varchar(3) NOT NULL,
       NR_ITEM_DA Smallint NOT NULL,
       NR_ADICAO_DI Varchar(3) NOT NULL,
       NR_ITEM_DI Smallint NOT NULL,
       NR_DI Varchar(10) NOT NULL,
       QTDE Double precision DEFAULT 0 NOT NULL,
       VL_UNITARIO Double precision DEFAULT 0 NOT NULL
);

CREATE TABLE IMP_LI_ANUENCIA (
       NR_LI Varchar(12) NOT NULL,
       CODIGO_PROCESSO Integer NOT NULL,
       VALOR_ANUENCIA Numeric(15,2) DEFAULT 0 NOT NULL,
       PRIMARY KEY (CODIGO_PROCESSO,NR_LI)
);

CREATE TABLE IMP_LI_PADRAO (
       LOCAL_COND_VENDA Varchar(30) NOT NULL,
       CODIGO_PROCESSO Integer NOT NULL,
       VINCULO_PRECO Varchar(1),
       NUMERO_DA Varchar(12),
       NR_CTR_ANTECIPADO Varchar(8),
       NR_BANCO_ANTECIPADO Varchar(5),
       NR_AGENCIA_ANTECIPADO Varchar(4),
       NR_CTR_AVISTA Varchar(8),
       NR_BANCO_AVISTA Varchar(5),
       NR_AGENCIA_AVISTA Varchar(4),
       TIPO_PARCELAS_180 Varchar(1),
       IN_TAXA_JUROS_180 Varchar(1),
       INDICADOR_PERIOD_180 Varchar(1),
       QTDE_PARCELAS_180 Varchar(3),
       PERIODICIDADE_180 Varchar(3),
       COD_TAXA_JUROS_180 Varchar(4),
       VAL_TAXA_JUROS_180 Double precision,
       TIPO_PARCELAS_360 Varchar(1),
       IN_TAXA_JUROS_360 Varchar(1),
       INDICADOR_PERIOD_360 Varchar(1),
       QTDE_PARCELAS_360 Varchar(3),
       PERIODICIDADE_360 Varchar(3),
       COD_TAXA_JUROS_360 Varchar(4),
       VAL_TAXA_JUROS_360 Double precision,
       CD_MET_VALORACAO Char(2) DEFAULT '01' NOT NULL,
       NR_ROF Varchar(8),
       PRIMARY KEY (CODIGO_PROCESSO)
);

CREATE TABLE IMP_NVINCULO_CERTICADO_JM (
       CODIGO Integer NOT NULL,
       CONSTRAINT PK_IMP_NVINCULO_CERTICADO_JM PRIMARY KEY (CODIGO)
);

CREATE TABLE IMP_PROCESSO_ACRESCIMO (
       CD_PROCESSO Integer NOT NULL,
       CD_ACRESCIMO Smallint NOT NULL,
       VL_MOEDA Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_MOEDA_NAC Numeric(15,2) DEFAULT 0 NOT NULL,
       CD_MOEDA Varchar(3) NOT NULL,
       PRIMARY KEY (CD_PROCESSO,CD_ACRESCIMO)
);

CREATE TABLE IMP_PROCESSO_ADICOES (
       CD_PROCESSO Integer NOT NULL,
       CD_INSCR_ESTAUAL Varchar(14) NOT NULL,
       CD_DESTINO Char(2) NOT NULL,
       CD_UTILIZACAO Char(2) NOT NULL,
       CD_NCM Varchar(8) NOT NULL,
       CD_NCM_PROD Varchar(8) NOT NULL,
       VL_FOB_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_FRETE_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_SEGURO_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_II_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_IPI_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       NR_ADICAO Integer NOT NULL,
       VL_PIS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_COFINS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       CD_INCOTERM Varchar(3),
       VL_MULTAS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_TAXAS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_CAPATAZIA Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_PL_CARGA Double precision NOT NULL,
       NR_PEXPAM Varchar(9),
       CD_PRODUTO_SUF Varchar(11),
       CD_TRIBUTO_ICMS Varchar(4),
       VL_COEFICIENTE_ICMS Double precision,
       NR_LI Varchar(12),
       NM_EXPORTADOR Varchar(60),
       VL_ALIQ_II Numeric(9,2) DEFAULT 0,
       VL_ALIQ_IPI Numeric(9,2) DEFAULT 0,
       VL_ALIQ_PIS Numeric(9,2) DEFAULT 0,
       VL_ALIQ_COFINS Numeric(9,2) DEFAULT 0,
       VL_ANTIDUMPING_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_CIDE_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       CD_TRIBUTO_SI Varchar(4),
       VL_COEFICIENTE_SI Double precision DEFAULT 0 NOT NULL,
       CD_TRIBUTO_FPS Varchar(4),
       VL_COEFICIENTE_FPS Double precision DEFAULT 0 NOT NULL,
       CD_MOEDA_FOB Varchar(3),
       VL_TX_MOEDA_FOB Double precision DEFAULT 0 NOT NULL,
       VL_FOB_MNEG_NAC Numeric(15,2),
       VL_FRETE_NAC Numeric(15,2),
       VL_SEGURO_NAC Numeric(15,2),
       VL_ADUANEIRO_NAC Numeric(15,2),
       QTDE_ESTATISTICA Numeric(15,5),
       CD_PAIS_EXPORTADOR Char(3),
       NM_FABRICANTE Varchar(60),
       CD_PAIS_FABRICANTE Char(3),
       CD_AUSENCIA_FABRICANTE Char(1),
       VL_II_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_IPI_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_PIS_DEVIDO Float DEFAULT 0 NOT NULL,
       VL_COFINS_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       DB_DOC_SUSP_PAG_DES Varchar(20),
       DB_DOC_SUSP_PAG_VAL Date,
       DB_DOC_SUSP_PAG_TIPO Char(1),
       DB_DOC_SUSP_PAG_TP_OPE Char(1),
       VL_FOB_NNEG_X Numeric(15,2),
       VL_FOB_MNEG Numeric(15,2),
       CONSTRAINT PK_IMP_PROCESSO_ADICOES PRIMARY KEY (CD_PROCESSO,NR_ADICAO)
);

CREATE TABLE IMP_PROCESSO_ADICOES_ITEM (
       CD_PROCESSO Integer NOT NULL,
       DET_PRODUTO Integer NOT NULL,
       NM_SUFRAMA Varchar(255) NOT NULL,
       NM_ESP_TECNICA Varchar(255),
       QUANTIDADE Double precision DEFAULT 0 NOT NULL,
       NM_UNIDADE Varchar(10),
       VL_UNITARIO_DOLAR Double precision DEFAULT 0 NOT NULL,
       VL_UNITARIO Double precision DEFAULT 0,
       PESO_LIQUIDO Double precision DEFAULT 0,
       CD_PART_NUMBER Varchar(25),
       NR_ADICAO Integer NOT NULL,
       VL_TOTAL COMPUTED BY ( QUANTIDADE * VL_UNITARIO),
       NR_ITEM Integer NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_ADICOES_ITEM PRIMARY KEY (CD_PROCESSO,NR_ADICAO,NR_ITEM)
);

CREATE TABLE IMP_PROCESSO_CARGA (
       CODIGO_PROCESSO Integer NOT NULL,
       PER_ARMAZ Integer,
       DAT_VCTO_ARMAZ Date,
       VAL_PGOT_ARMAZ Double precision,
       VAL_CPL_PGTO_ARMAZ Double precision,
       DAT_PAGTO_DESOVA Date,
       DAT_EXEC_DESOVA Date,
       VAL_DESOVA Double precision,
       VAL_CPL_PGTO_DESOVA Double precision,
       DAT_PAGTO_CAP Date,
       VAL_PAGTO_CAP Double precision,
       VAL_CPL_PGTO_CAP Double precision,
       DAT_PAGTO_ARMAZ Date,
       VAL_3_PERIODO_ARMAZENAGEM Numeric(15,2) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_CARGA PRIMARY KEY (CODIGO_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_CONTAINER (
       NR_FILHOTE Varchar(18) NOT NULL,
       CODIGO_PROCESSO Integer NOT NULL,
       NR_SEQUENCIAL Integer NOT NULL,
       NR_CONTAINER Varchar(20),
       CAPACIDADE Varchar(2),
       SELOS Varchar(30),
       CUBAGEM Double precision DEFAULT 0,
       CONSTRAINT PK_IMP_PROCESSO_CONTAINER PRIMARY KEY (CODIGO_PROCESSO,NR_FILHOTE,NR_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_DEDUCAO (
       CD_PROCESSO Integer NOT NULL,
       CD_DEDUCAO Smallint NOT NULL,
       CD_MOEDA Varchar(3) NOT NULL,
       VL_MOEDA Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_MOEDA_NAC Numeric(15,2) DEFAULT 0 NOT NULL,
       PRIMARY KEY (CD_PROCESSO,CD_DEDUCAO)
);

CREATE TABLE IMP_PROCESSO_DE_MERCOSUL (
       ID_SEQUENCIAL Integer NOT NULL,
       CD_PROCESSO Integer NOT NULL,
       NR_DE_MERCOSUL Varchar(16) NOT NULL,
       NR_RE_INICIAL Varchar(4) NOT NULL,
       NR_RE_FINAL Varchar(4) NOT NULL,
       PRIMARY KEY (CD_PROCESSO,ID_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_DI (
       ID_SEQUENCIAL Integer NOT NULL,
       CD_PROCESSO Integer NOT NULL,
       CD_TP_PROCESSO Smallint NOT NULL,
       NR_PROCESSO_INSTR Varchar(20) NOT NULL,
       VL_TX_FOB Double precision DEFAULT 0 NOT NULL,
       VL_TX_FRETE Double precision DEFAULT 0 NOT NULL,
       VL_TX_SEGURO Double precision DEFAULT 0 NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_DI PRIMARY KEY (CD_PROCESSO,ID_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_DOC_INSTRUCAO (
       CODIGO_PROCESSO Integer NOT NULL,
       NR_SEQUENCIAL Integer NOT NULL,
       CD_TIPO_DOC_INSTR Varchar(2) NOT NULL,
       NR_DOC_INSTR Varchar(25) NOT NULL,
       NR1 Varchar(20),
       NR2 Varchar(20),
       CONSTRAINT PK_IMP_PROCESSO_DOC_INSTRUCAO PRIMARY KEY (CODIGO_PROCESSO,NR_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_INFO_COMP_DI (
       CD_TP_IMPORADOR Char(1) DEFAULT '1' NOT NULL,
       NR_IMPORTADOR Varchar(14),
       CD_PROCESSO Integer NOT NULL,
       CD_PAIS_IMPORTADOR Varchar(3),
       NM_IMPORTADOR Varchar(60),
       NR_TEL_IMPORTADOR Varchar(15),
       ED_LOGR_IMPORTADOR Varchar(40),
       ED_NR_IMPORTADOR Varchar(6),
       ED_COMPL_IMPO Varchar(21),
       ED_BA_IMPORTADOR Varchar(25),
       ED_MUN_IMPORTADOR Varchar(25),
       ED_UF_IMPORTADOR Varchar(2),
       ED_CEP_IMPORTADOR Varchar(8),
       IN_OPERACAO_FUNDAP Char(1) DEFAULT 'N' NOT NULL,
       CD_TIPO_CONSIG Char(1),
       NR_CONSIGNATARIO Varchar(14),
       PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_LI (
       CD_PROCESSO Integer NOT NULL,
       ALIQ_II Double precision DEFAULT 0 NOT NULL,
       CD_NCM Varchar(8),
       ALIQ_IPI Double precision DEFAULT 0 NOT NULL,
       IPI_ALIQ_REDUCAO Double precision DEFAULT 0 NOT NULL,
       PIS_CODIGO Smallint DEFAULT 5,
       NR_ROF_BACEN Varchar(10),
       PIS_FUNDAMENTO Smallint,
       II_ACORDO_CODIGO Smallint DEFAULT 0 NOT NULL,
       NR_ADICAO Smallint DEFAULT 0 NOT NULL,
       ALIQ_PIS Double precision DEFAULT 0 NOT NULL,
       II_ACORDO_ALIQ Double precision DEFAULT 0 NOT NULL,
       ALIQ_COFINS Double precision DEFAULT 0 NOT NULL,
       II_ACORDO_TIPO Smallint,
       II_ACORDO_NR Varchar(3),
       NR_LI Varchar(12) NOT NULL,
       II_EX_CODIGO Smallint DEFAULT 0 NOT NULL,
       IPI_CD_TP_REGIME Varchar(1) DEFAULT '4' NOT NULL,
       IPI_NR_NOTA_COMP_TIPI Varchar(2),
       IN_STATUS Varchar(1),
       NR_DA Varchar(12),
       CD_APLIC_MERCADORIA Char(1) DEFAULT '0' NOT NULL,
       CD_COND_MERCADORIA Char(1) DEFAULT '0' NOT NULL,
       CD_COBERT_CAMBIAL Char(1) NOT NULL,
       CD_MOTIVO_ADM_TEMPORARIA Smallint DEFAULT 0 NOT NULL,
       ANT_NM_UN_ESPECIFICA Varchar(15),
       ANT_QT_MERC_UN_ESPECIFICA Double precision,
       ANT_VL_ALIQ_ESPECIFICA Double precision,
       ANT_ADVALOREM Double precision,
       ANT_BASE_CALCULO Double precision,
       CD_TP_ALIQ_IPT Char(1) DEFAULT '1' NOT NULL,
       COFINS_NM_UN_ALIQ_ESP_IPT Varchar(15),
       COFINS_QT_MERC_UN_ALIQ_ESP Integer,
       COFINS_VL_ALIQ_ESPEC_IPT Double precision,
       PIS_NM_UN_ALIQ_ESP_IPT Varchar(15),
       PIS_QT_MERC_UN_ALIQ_ESP Integer,
       PIS_VL_ALIQ_ESPEC_IPT Double precision,
       CD_DESTAQUE_CIDE Varchar(3),
       ALIQ_PIS_REDUZIDA Double precision DEFAULT 0 NOT NULL,
       ALIQ_COFINS_REDUZIDA Double precision DEFAULT 0 NOT NULL,
       II_NBM_EX_CODIGO Smallint DEFAULT 0 NOT NULL,
       IN_PIS_COFINS_RED_BC Char(1) DEFAULT 'N' NOT NULL,
       PIS_CD_FUND_RED_BC Smallint,
       PIS_ALIQ_REQ_BC Double precision DEFAULT 0 NOT NULL,
       ALIQ_II_REDUCAO Double precision DEFAULT 0 NOT NULL,
       ALIQ_II_PER_REDUCAO Double precision DEFAULT 0 NOT NULL,
       CD_EXTARIFARIO Integer,
       VL_ROF Numeric(15,2) DEFAULT 0 NOT NULL,
       CD_MULTA Integer DEFAULT 0 NOT NULL,
       IN_ORIGEM_ALIQ_PIS_COFINS Varchar(3),
       VL_MULTA Numeric(15,2) DEFAULT 0 NOT NULL,
       NR_RE Varchar(15),
       IN_TP_VINCULO_PRECO Varchar(1),
       CONSTRAINT PK_IMP_PROCESSO_LI PRIMARY KEY (CD_PROCESSO,NR_LI)
);

CREATE TABLE IMP_PROCESSO_LI_180 (
       CD_PROCESSO Integer NOT NULL,
       IN_TP_PARCELAS_180 Varchar(1),
       IN_INDICADOR_PERIOD_180 Varchar(1),
       QTD_PARCELAS_180 Integer,
       PERIODICIDADE_180 Integer,
       PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_LI_360 (
       CD_PROCESSO Integer NOT NULL,
       IN_TP_PARCELAS_360 Varchar(1),
       IN_INDICADOR_PERIOD_360 Varchar(1),
       QTD_PARCELAS_360 Integer,
       PERIODICIDADE_360 Integer,
       PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_LI_ATO_LEGAL (
       CD_PROCESSO Integer NOT NULL,
       CD_ASSUNTO Integer NOT NULL,
       CD_EX Varchar(3),
       CD_TIPO Varchar(5),
       CD_ORGAO Varchar(6),
       CD_NUMERO Varchar(6),
       CD_ANO Varchar(4),
       CD_TP_ALIQUOTA Char(1) DEFAULT '0' NOT NULL,
       VL_ALIQUOTA Double precision DEFAULT 0 NOT NULL,
       NR_ADICAO Integer NOT NULL,
       NR_LI Varchar(12),
       CONSTRAINT PK_IMP_PROCESSO_LI_ATO_LEGAL PRIMARY KEY (CD_PROCESSO,NR_ADICAO,CD_ASSUNTO)
);

CREATE TABLE IMP_PROCESSO_LI_CONTRATO (
       CD_PROCESSO Integer NOT NULL,
       NR_SEQUENCIAL Integer NOT NULL,
       NR_CONTRATO Varchar(10) NOT NULL,
       NM_BANCO Varchar(5),
       NM_AGENCIA Varchar(4) NOT NULL,
       IN_TIPO Char(1) DEFAULT '1' NOT NULL,
       PRIMARY KEY (CD_PROCESSO,NR_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_LI_DE_MERCOSUL (
       ID_SEQUENCIAL Integer NOT NULL,
       CD_PROCESSO Integer NOT NULL,
       NR_DE_ADICAO_MERCOSUL Varchar(16) NOT NULL,
       NR_RE_ADICAO_INICIAL Varchar(4) NOT NULL,
       NR_RE_ADICAO_FINAL Varchar(4) NOT NULL,
       CD_PAIS_CERTIFICADO Varchar(2),
       NR_DI_CERTIFICAD Varchar(16),
       NR_ITEM_CERTIFICADO Varchar(4),
       QT_UNIDADE_MERCOSUL Double precision,
       IN_TP_CERTIFICADO Char(1) DEFAULT '0' NOT NULL,
       NR_LI Varchar(12) NOT NULL,
       PRIMARY KEY (CD_PROCESSO,NR_LI,ID_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_OUTRAS_TAXAS (
       ID_SEQUENCIAL Integer NOT NULL,
       CD_PROCESSO Integer NOT NULL,
       CD_MOEDA Smallint NOT NULL,
       VL_TX_CONVERSAO Double precision DEFAULT 0 NOT NULL,
       PRIMARY KEY (CD_PROCESSO,ID_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_PGTO_VINCULADO (
       CD_PROCESSO Integer NOT NULL,
       CD_TRIBUTO Varchar(4) NOT NULL,
       VL_TRIBUTO Numeric(15,2) DEFAULT 0 NOT NULL,
       PRIMARY KEY (CD_PROCESSO,CD_TRIBUTO)
);

CREATE TABLE IMP_PROCESSO_TAXAS_DI (
       CD_PROCESSO Integer NOT NULL,
       CD_MOEDA Varchar(3) NOT NULL,
       VL_TX_CONVERSAO Double precision DEFAULT 0 NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_TAXAS_DI PRIMARY KEY (CD_PROCESSO,CD_MOEDA)
);

CREATE TABLE IMP_PROCESSO_TRIBUTOS_PAGOS (
       ID_SEQUENCIAL Integer NOT NULL,
       CD_BANCO Varchar(3),
       CODIGO_PROCESSO Integer NOT NULL,
       AGENCIA Varchar(4),
       CONTA Varchar(19),
       CD_TRIBUTO Varchar(4) NOT NULL,
       VL_TRIBUTO Numeric(15,2) DEFAULT 0 NOT NULL,
       IN_TESOURARIA_MXM Char(1) DEFAULT 'N' NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_TRIBUTOS_PAGOS PRIMARY KEY (CODIGO_PROCESSO,ID_SEQUENCIAL)
);

CREATE TABLE IMP_PROCESSO_TRIUMPH (
       CD_PROCESSO Integer NOT NULL,
       CHIBATAO_RPS Integer DEFAULT 0,
       CHIBATAO_NF Integer DEFAULT 0,
       CHIBATAO_EMISSAO Date,
       CHIBATAO_VL_BRUTO Double precision DEFAULT 0,
       LSCHOPAN_NF Integer DEFAULT 0,
       LSCHOPAN_EMISSAO Date,
       LSCHOPAN_VL_BRUTO Double precision DEFAULT 0,
       CEVA_NF_NF Integer DEFAULT 0,
       CEVA_NF_EMISSAO Date,
       CEVA_NF_VL_BRUTO Double precision DEFAULT 0,
       CEVA_ND_ND Integer DEFAULT 0,
       CEVA_ND_EMISSAO Date,
       CEVA_ND_VL_BRUTO Double precision DEFAULT 0,
       CONSTRAINT PK_IMP_PROCESSO_TRIUMPH PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_VALORES (
       CD_PROCESSO Integer NOT NULL,
       VL_FOB_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_FRETE_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_SEGURO_DOLAR Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_II_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_IPI_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_PIS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_COFINS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_MULTAS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_TAXAS_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       IN_STATUS Char(1) DEFAULT 'N',
       NM_EXPORTADOR Varchar(30),
       VL_CAPATAZIA Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_ANTIDUMPING_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_CIDE_RECOLHER Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_II_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_IPI_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_COFINS_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       VL_PIS_DEVIDO Numeric(15,2) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_VALORES PRIMARY KEY (CD_PROCESSO)
);

CREATE TABLE IMP_PROCESSO_VOLUMES (
       CODIGO_PROCESSO Integer NOT NULL,
       NR_SEQUENCIAL Integer NOT NULL,
       COD_VOLUMES Varchar(2) NOT NULL,
       QTD_VOLUMES Integer NOT NULL,
       CONSTRAINT PK_IMP_PROCESSO_VOLUMES PRIMARY KEY (CODIGO_PROCESSO,NR_SEQUENCIAL)
);

CREATE TABLE IMP_SEFAZ (
       CODIGO_PROCESSO Integer NOT NULL,
       VAL_BASE_INDUST Double precision,
       VAL_IMP_INDUST Double precision,
       VAL_BASE_USO Double precision,
       VAL_IMP_USO Double precision,
       VAL_BASE_COMER Double precision,
       VAL_IMP_COMER Double precision,
       INSC_INDUST Varchar(12),
       INSC_USO Varchar(12),
       INSC_COMER Varchar(12),
       PRIMARY KEY (CODIGO_PROCESSO)
);

CREATE TABLE TAB_ACRESCIMO_APLICACAO (
       CD_ACRESCIMO Smallint NOT NULL,
       CD_INCOTERM Char(3) NOT NULL,
       CONSTRAINT PK_TAB_ACRESCIMO_APLICACAO PRIMARY KEY (CD_INCOTERM,CD_ACRESCIMO)
);

CREATE TABLE TAB_ACRESCIMO_VALORACAO (
       CODIGO Smallint NOT NULL,
       DESCRICAO Varchar(60) NOT NULL,
       CONSTRAINT PK_TAB_ACRESCIMO_VALORACAO PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_DOC_INSTRUCAO (
       CODIGO Varchar(2) NOT NULL,
       DESCRICAO Varchar(120),
       PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_LOC_ARMAZENAGEM (
       CODIGO Varchar(1) NOT NULL,
       DESCRICAO Varchar(20),
       PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_MOEDAS (
       CODIGO Varchar(3) NOT NULL,
       DESCRICAO Varchar(40),
       TAXA_CONVERSAO Double precision,
       VIGENCIA_INICIO_TAXA Date,
       VIGENCIA_FIM_TAXA Date,
       PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_PAIS (
       CODIGO Varchar(3) NOT NULL,
       NOME Varchar(120),
       PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_SET_REC_ALFANDEGADO (
       ORGAO Varchar(7) NOT NULL,
       RECINTO Varchar(7) NOT NULL,
       SETOR Varchar(3) NOT NULL,
       NOME Varchar(30),
       PRIMARY KEY (ORGAO,RECINTO,SETOR)
);

CREATE TABLE TAB_TIPO_DECLARACAO (
       CODIGO Varchar(2) NOT NULL,
       DESCRICAO Varchar(120),
       PRIMARY KEY (CODIGO)
);

CREATE TABLE TAB_TIPO_EMBALAGEM (
       CODIGO Varchar(2) NOT NULL,
       DESCRICAO Varchar(120),
       PRIMARY KEY (CODIGO)
);

ALTER TABLE IMPORTACAO ADD FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX IDX_IMPORTACAO_1 ON IMPORTACAO(DATA_DA_DI);
CREATE INDEX IDX_IMPORTACAO_2 ON IMPORTACAO(DATA_LIBERACAO);
CREATE INDEX IDX_IMPORTACAO_3 ON IMPORTACAO(DT_ENTRAGA_TRANSPORTADOR);
CREATE INDEX IDX_IMPORTACAO_4 ON IMPORTACAO(CODIGO_CLIENTE,IDT_EMBARQUE);
CREATE INDEX IMPORTACAO2 ON IMPORTACAO(NUMERO_DI);
CREATE INDEX IMPORTACAO_NR_FILHOTE_IDX ON IMPORTACAO(NUMERO_FILHOTE);
CREATE INDEX IMPORTACAO_NUMERO_DA ON IMPORTACAO(NUMERO_DA);
ALTER TABLE IMP_LI_ANUENCIA ADD CONSTRAINT IMPORT_ANUENCIA FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_LI_PADRAO ADD FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_ADICOES ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX IDX_IMP_PROCESSO_ADICOES_1 ON IMP_PROCESSO_ADICOES(NR_LI);
ALTER TABLE IMP_PROCESSO_ADICOES_ITEM ADD CONSTRAINT FK_IMP_PROCESSO_ADICOES_ITEM_1 FOREIGN KEY (CD_PROCESSO,NR_ADICAO) REFERENCES IMP_PROCESSO_ADICOES(CD_PROCESSO,NR_ADICAO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_CARGA ADD CONSTRAINT FK_IMP_PROCESSO_CARGA_0 FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_CARGA ADD CONSTRAINT FK_IMP_PROCESSO_CARGA_1 FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_CONTAINER ADD CONSTRAINT FK_IMP_PROCESSO_CONTAINER_0 FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_DEDUCAO ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO);
ALTER TABLE IMP_PROCESSO_DE_MERCOSUL ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_DI ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_DOC_INSTRUCAO ADD CONSTRAINT FK_IMP_PROCESSO_DOC_INSTRUCAO_0 FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_INFO_COMP_DI ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_LI ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_LI_180 ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_LI_360 ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_LI_CONTRATO ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_LI_DE_MERCOSUL ADD CONSTRAINT FK_IMP_PROCESSO_LI_DE_MERCOSU_1 FOREIGN KEY (CD_PROCESSO,NR_LI) REFERENCES IMP_PROCESSO_LI(CD_PROCESSO,NR_LI);
ALTER TABLE IMP_PROCESSO_OUTRAS_TAXAS ADD CONSTRAINT FK_IMP_PROCESSO_OUTRAS_TAXAS_1 FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_PGTO_VINCULADO ADD FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_TAXAS_DI ADD CONSTRAINT FK_IMP_PROCESSO_TAXAS_DI_1 FOREIGN KEY (CD_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_TRIBUTOS_PAGOS ADD FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_PROCESSO_VOLUMES ADD CONSTRAINT FK_IMP_PROCESSO_VOLUMES_0 FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE IMP_SEFAZ ADD FOREIGN KEY (CODIGO_PROCESSO) REFERENCES IMPORTACAO(CODIGO_PROCESSO) ON UPDATE CASCADE ON DELETE CASCADE;
/***********************************/
/*              Views              */
/***********************************/

CREATE VIEW PROC_IMPORT(NUMERO_DI,CODIGO_CLIENTE,NOME_CLIENTE,CODIGO_PROCESSO,LOCAL_ARMAZEN,DATA_ABERTURA,NRO_CONTRATO_CAMBIO,DAT_FEC_CAMBIO,DATA_DA_DI,TIPO_PROCESSO,VALOR_FOB_LOC_EMB,VALOR_FRETE_PRAPAID,VALOR_FRETE_COLECT,IDT_EMBARQUE,VALOR_SEGURO,IDT_DI,DATA_CHEGADA,DATA_ENTRADA_SEFAZ,DATA_SAIDA_SEFAZ,DATA_LIBERACAO,CANAL,STATUS_PROCESSO,PENDICIA_MAPA,VIA_TRANSPORTE,VALOR_CIF,PER_ARMAZ,DATA_RECEBIMENTO,DAT_PAGTO_ARMAZ,DAT_VCTO_ARMAZ,DAT_PAGTO_CAP,DAT_PAGTO_DESOVA,DAT_EXEC_DESOVA,VAL_PGTO_ARMAZ,VAL_CPL_PGTO_ARMAZ,VAL_DESOVA,VAL_CPL_PGTO_DESOVA,VAL_PAGTO_CAP,VAL_CPL_PGTO_CAP,PRIORIDADE,AFTN,DATA_PRIORIDADE,TRANSPORTADOR,DATA_PARAM,DATA_MANTRA,QTDE_ADICOES,TAXA_SISCOMEX,PESO_LIQUIDO,INS_SEFAZ,PESO_BRUTO,TAXA_DOLAR_DI,VAL_BASE_INDUST,VAL_IMP_INDUST,ACAO_FISCAL,DI_INTERNA,ENTRADA_MIN_AGRIC,SAIDA_MIN_AGRIC,NUMERO_FILHOTE,TIPO_DE_DI,VALOR_FOB_MOEDA_NAC,MOEDA_FOB,VALOR_FRETE_MOEDA_NAC,MOEDA_FRETE,DT_CHEGADA,VALOR_FRETE_TER_NAC,MOEDA_SEGURO,VALOR_SEGURO_MOEDA_NAC,VALOR_FOB_PEXPAM,ICOTERM,DT_ENTREGA)
AS
SELECT
       A.CODIGO_CLIENTE,
       C.NOME_CLIENTE,
       A.CODIGO_PROCESSO,
       A.LOCAL_ARMAZEN,
       A.DATA_ABERTURA,
       A.NRO_CONTRATO_CAMBIO,
       A.DAT_FEC_CAMBIO,
       A.NUMERO_DI,
       A.DATA_DA_DI,
       A.TIPO_PROCESSO,
       A.VALOR_FOB_LOC_EMB,
       A.VALOR_FRETE_PRAPAID,
       A.VALOR_FRETE_COLECT,
       A.VALOR_SEGURO,
       A.IDT_EMBARQUE,
       A.IDT_DI,
       A.DATA_CHEGADA,
       A.DATA_ENTRADA_SEFAZ,
       A.DATA_SAIDA_SEFAZ,
       A.DATA_LIBERACAO,
       A.CANAL,
       A.STATUS_PROCESSO,
       A.PENDICIA_MAPA,
       A.VIA_TRANSPORTE,
       A.VALOR_CIF,
       A.DATA_RECEBIMENTO,
       B.PER_ARMAZ,
       B.DAT_PAGTO_ARMAZ,
       B.DAT_VCTO_ARMAZ,
       B.DAT_PAGTO_CAP,
       B.DAT_PAGTO_DESOVA,
       B.DAT_EXEC_DESOVA,
       B.VAL_PGOT_ARMAZ,
       B.VAL_CPL_PGTO_ARMAZ,
       B.VAL_DESOVA,
       B.VAL_CPL_PGTO_DESOVA,
       B.VAL_PAGTO_CAP,
       B.VAL_CPL_PGTO_CAP,
       A.PRIORIDADE,
       A.DATA_PRIORIDADE,
       A.NOME_FISCAL,
       A.DATA_PARAM,
       A.AGENTE_TRANSPORTADOR,
       A.DATA_MANTRA,
       A.QTDE_ADICOES,
       A.TAXA_UTILIZACAO_SISCOMEX,
       A.PESO_LIQUIDO,
       A.PESO_BRUTO,
       A.INSCRICAO_SEFAZ,
       A.TAXA_DOLAR_DI,
       D.VAL_BASE_INDUST,
       D.VAL_IMP_INDUST,
       A.ACAO_FISCAL,
       A.DI_INTERNA,
       A.ENTRADA_MIN_AGRIC,
       A.SAIDA_MIN_AGRIC,
       A.NUMERO_FILHOTE,
       A.TIPO_DE_DI,
       A.VALOR_FOB_MOEDA_NAC,
       A.MOEDA_FOB,
       A.VALOR_FRETE_MOEDA_NAC,
       A.MOEDA_FRETE,
       A.VALOR_FRETE_TER_NAC,
       A.MOEDA_SEGURO,
       A.VALOR_SEGURO_MOEDA_NAC,
       A.VALOR_FOB_PEXPAM,
       A.ICOTERM,
       A.DT_ENTRAGA_TRANSPORTADOR,
       A.DATA_CHEGADA
FROM IMPORTACAO A
      LEFT OUTER JOIN IMP_PROCESSO_CARGA B
      ON B.CODIGO_PROCESSO = A.CODIGO_PROCESSO
      LEFT OUTER JOIN CLIENTE C
      ON C.CODIGO_CLIENTE  = A.CODIGO_CLIENTE
      LEFT OUTER JOIN IMP_SEFAZ D
      ON D.CODIGO_PROCESSO = A.CODIGO_PROCESSO;

COMMIT WORK;
SET TERM ^ ;
COMMIT WORK^
SET TERM ; ^

/* Grant role for this database */


/* Grant permissions for this database */
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON CLIENTE TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON EMPRESA TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMPORTACAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_DI_COMPLEMENTAR TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_LI_ANUENCIA TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_LI_PADRAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_NVINCULO_CERTICADO_JM TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_ACRESCIMO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_ADICOES TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_ADICOES_ITEM TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_CARGA TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_CONTAINER TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_DEDUCAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_DE_MERCOSUL TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_DI TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_DOC_INSTRUCAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_INFO_COMP_DI TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI_180 TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI_360 TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI_ATO_LEGAL TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI_CONTRATO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_LI_DE_MERCOSUL TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_OUTRAS_TAXAS TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_PGTO_VINCULADO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_TAXAS_DI TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_TRIBUTOS_PAGOS TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_TRIUMPH TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_VALORES TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_PROCESSO_VOLUMES TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON IMP_SEFAZ TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON PROC_IMPORT TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_ACRESCIMO_APLICACAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_ACRESCIMO_VALORACAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_DOC_INSTRUCAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_LOC_ARMAZENAGEM TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_MOEDAS TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_PAIS TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_SET_REC_ALFANDEGADO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_TIPO_DECLARACAO TO PUBLIC WITH GRANT OPTION;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON TAB_TIPO_EMBALAGEM TO PUBLIC WITH GRANT OPTION;

COMMIT WORK;
